name: flutter_academy_graduation
description: FlutterAcademyGraduationArtWork


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  http: 
  test: ^1.5.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

