name: flutter_academy_graduation
description: FlutterAcademyGraduationArtWork


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.10
  firebase_auth: 
  http: 
  test: ^1.5.1
  convex_bottom_bar:
  dynamic_theme:
  provider:
  share_plus:
  screenshot:
  path_provider:
  lottie:
  favorite_button: ^0.0.4
  cached_network_image:


  cupertino_icons: ^1.0.2
assets:
  - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

