# This is a basic workflow to help you get started with Actions

name: testing

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  component_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
